### ISSUE TITLE
Program operation failed

### ISSUE THREAD

**Issue by charmowen** [zzdang/cascade_rcnn_gluon#1]
cascade_rcnn_vgg16_pruned_voc
Traceback (most recent call last):
  File "scripts/detection/cascade_rcnn/train_cascade_rcnn.py", line 490, in <module>
    net = get_model(net_name, pretrained_base=True)
  File "/home/cascade_rcnn_gluon/gluoncv/model_zoo/model_zoo.py", line 115, in get_model
    net = models[name](**kwargs)
  File "/home/cascade_rcnn_gluon/gluoncv/model_zoo/cascade_rcnn/cascade_rcnn.py", line 672, in cascade_rcnn_vgg16_pruned_voc
    base_network = vgg16_pruned(pretrained=pretrained_base)
  File "/home/cascade_rcnn_gluon/gluoncv/model_zoo/cascade_rcnn/vgg16_pruned.py", line 127, in vgg16_pruned
    return get_vgg(16, **kwargs)
  File "/home/cascade_rcnn_gluon/gluoncv/model_zoo/cascade_rcnn/vgg16_pruned.py", line 109, in get_vgg
    net.load_parameters('./models/VGG_16_fc2048_prune_cascade.params',ctx=ctx)
AttributeError: 'VGG' object has no attribute 'load_parameters'

**Comment by zzdang** [comment]
Do you use "python setup.py install" to build cascade_rcnn_gluon before training?

**Comment by zzdang** [comment]
soory, you should use load_params.py to convert the vgg16_pruned pretained params to vgg 16_pruned_cascade params
you can also look at  readme ,I update it

**Comment by lininglouis** [comment]
@charmowen 
It seems that you used elder version of mxnet/gluon.  try "load_params()" instead(it has been deprecated in the latest mxnet).
load_parameters should work with latest mxnet/gluon
